# 项目相关配置
ruoyi:
  # 名称
  name: upwisdom
  # 版本
  version: 2.1.0
  # 版权年份
  copyrightYear: 2019
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/upwisdom/uploadPath，Linux配置 /home/ruoyi/uploadPath）
#  profile: D:/upwisdom/uploadPath
#  profileTwo: D:/upwisdom/uploadPathTwo
  profile: /home/ferghana/install/flink-1.11.1/lib
  profileTwo: /home/ferghana/software/flink-1.11.1/lib
#   获取ip地址开关
  addressEnabled: true

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8079
  servlet:
    # 应用的访问路径
#    context-path: /prod-api
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30


# 日志配置
logging:
  level:
    com.unityup: debug
    org.springframework: warn

# Spring配置
spring:
  activiti:
    #      database-schema: ACT
    database-schema-update: true
    check-process-definitions: false
    db-identity-used: false  #身份信息表使用的是视图所以不用新建
  security:
    basic:
      enabled: false
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
# 附加文件的选用
  profiles: 
    active: dev
  # 文件上传
  servlet:
     multipart:
       # 单个文件大小
       max-file-size:  100MB
       # 设置总上传的文件大小
       max-request-size:  200MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # redis 配置
  redis:
    # 地址
    host: localhost
    # 端口，默认为6379
    port: 6379
    # 密码
    password: 
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

# token配置
token:
    # 令牌自定义标识
    header: Authorization
    # 令牌秘钥
    secret: abcdefghijklmnopqrstuvwxyz
    # 令牌有效期（默认30分钟）
    expireTime: 14400
  
# MyBatis配置
mybatis:
    # 搜索指定包别名
    typeAliasesPackage: com.skyon.project.**.domain
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath*:mybatis/**/*Mapper.xml
    # 加载全局的配置文件
    configLocation: classpath:mybatis/mybatis-config.xml
  

# PageHelper分页插件
pagehelper: 
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql 

# 防止XSS攻击
xss: 
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*
  
# 代码生成
gen: 
  # 作者
  author: skyon
  # 默认生成包路径 system 需改成自己的模块名称 如 system monitor tool
  packageName: com.skyon.project.system
  # 自动去除表前缀，默认是true
  autoRemovePre: false
  # 表前缀（生成类名不会包含表前缀，多个用逗号分隔）
  tablePrefix: sys_

admin_user_id: 1

aggregator:
  h2:
    url: jdbc:h2:~/H2Data/cboard;AUTO_SERVER=TRUE;LOG=0;UNDO_LOG=0
    database:
      name: cboard
    cleanjob:
      quarz: 0 1 0 * * ?
